### ISSUE TITLE
JSPM

### ISSUE THREAD

**Issue by Dutchboy** [conclurer/ionic2-systemjs#11]
Hi!

I just stumbled across your -very good and working- ionic2+systemjs seed project... You seem very active on it. I'm grateful! Thanks for sharing it!

A question... What is your view about jspm doing the external package management?

Many thanks! Lars

**Comment by marvinscharle** [comment]
JSPM is IMO a very sophisticated project with many benefits over NPM when using in conjunction with SystemJS (since it is built to support SystemJS out-of-the-box).

I didn't have the chance of using JSPM for a "real" project - but I'm looking forward to it.

**Comment by Dutchboy** [comment]
... Two months ago, I've watched a course about the jspm, systemjs and ES6loader - explaining the differences and how they all fall together. I was new to it - trying to avoid ES6 and even Typescript. 

(((((The lather, because it's Microsoft and even though I've met Bill Gates a few times personally and do admire how they've done things in the past, I developed an allergy when it comes to their development contribution, EF .NET etc... )))))

But then I realized if even the Angular Team (read: Google) accepts / embraces Typescript, I should start to look into it. Wonderful, getting into C# again! :-) So, okay, learnt it / accepted it. Not a big thing.

ES6 (ES2015) - well nothing to add here - has been on my plate. Done. Or better, starting to get back to my original class-thinking I loved during the C# times... Feel happy about it. And comfortable with the fact it nicely can be transpiled to ES5.

ES6 Module loading. I love it. I do hate browserify and the likes. Hate is a big word. I try to avoid it. SystemJS and JSPM doesn't care which module notation it receives... For example, the course I mentioned, adds a development script showModuleRelationships and all it does is opening a new window, pointing to www.yuml.me, which creates a picture of all modules loaded ([The Below Code Produced This](http://yuml.me/diagram/plain/class/[jspm_packages/npm/babel-core@5.8.25.js%7Ccjs],[jspm_packages/npm/babel-core@5.8.25/browser.js%7Cglobal],[app.js%7Cesm],[jspm_packages/github/angular/bower-angular@1.4.7.js%7Ccjs],[klondike/klondike.js%7Cesm],[jspm_packages/github/fatlinesofcode/ngDraggable@0.1.8.js%7Ccjs],[jspm_packages/github/angular/bower-angular@1.4.7/angular.js%7Cglobal],[klondike/game.js%7Cesm],[klondike/board.js%7Cesm],[klondike/scoring.js%7Cesm],[jspm_packages/github/fatlinesofcode/ngDraggable@0.1.8/ngDraggable.js%7Cglobal],[jspm_packages/npm/underscore@1.8.3.js%7Ccjs],[cards/deck.js%7Cesm],[klondike/piles/tableauPile.js%7Cesm],[klondike/piles/remainderPile.js%7Cesm],[klondike/piles/foundationPile.js%7Cesm],[jspm_packages/github/angular/bower-angular-route@1.4.7.js%7Ccjs],[jspm_packages/npm/babel-runtime@5.8.25/helpers/create-class.js%7Ccjs],[jspm_packages/npm/babel-runtime@5.8.25/helpers/class-call-check.js%7Ccjs],[jspm_packages/npm/underscore@1.8.3/underscore.js%7Ccjs],[cards/card.js%7Cesm],[klondike/piles/pile.js%7Cesm],[jspm_packages/npm/babel-runtime@5.8.25/core-js/object/create.js%7Ccjs],[jspm_packages/github/angular/bower-angular-route@1.4.7/angular-route.js%7Cglobal],[jspm_packages/npm/babel-runtime@5.8.25/core-js/object/define-property.js%7Ccjs],[jspm_packages/npm/core-js@1.2.1/library/fn/object/create.js%7Ccjs],[jspm_packages/npm/core-js@1.2.1/library/fn/object/define-property.js%7Ccjs],[jspm_packages/npm/core-js@1.2.1/library/modules/$.js%7Ccjs],[jspm_packages/npm/babel-core@5.8.25.js]-%3E[jspm_packages/npm/babel-core@5.8.25/browser.js],[app.js]-%3E[jspm_packages/github/angular/bower-angular@1.4.7.js],[app.js]-%3E[jspm_packages/github/fatlinesofcode/ngDraggable@0.1.8.js],[app.js]-%3E[klondike/klondike.js],[jspm_packages/github/angular/bower-angular@1.4.7.js]-%3E[jspm_packages/github/angular/bower-angular@1.4.7/angular.js],[klondike/klondike.js]-%3E[jspm_packages/github/angular/bower-angular@1.4.7.js],[klondike/klondike.js]-%3E[klondike/game.js],[klondike/klondike.js]-%3E[klondike/board.js],[klondike/klondike.js]-%3E[klondike/scoring.js],[jspm_packages/github/fatlinesofcode/ngDraggable@0.1.8.js]-%3E[jspm_packages/github/fatlinesofcode/ngDraggable@0.1.8/ngDraggable.js],[klondike/game.js]-%3E[jspm_packages/github/angular/bower-angular@1.4.7.js],[klondike/game.js]-%3E[jspm_packages/npm/underscore@1.8.3.js],[klondike/game.js]-%3E[cards/deck.js],[klondike/game.js]-%3E[klondike/piles/tableauPile.js],[klondike/game.js]-%3E[klondike/piles/remainderPile.js],[klondike/game.js]-%3E[klondike/piles/foundationPile.js],[klondike/board.js]-%3E[jspm_packages/github/angular/bower-angular@1.4.7.js],[klondike/board.js]-%3E[jspm_packages/github/angular/bower-angular-route@1.4.7.js],[klondike/scoring.js]-%3E[jspm_packages/npm/babel-runtime@5.8.25/helpers/create-class.js],[klondike/scoring.js]-%3E[jspm_packages/npm/babel-runtime@5.8.25/helpers/class-call-check.js],[jspm_packages/github/fatlinesofcode/ngDraggable@0.1.8/ngDraggable.js]-%3E[jspm_packages/github/angular/bower-angular@1.4.7.js],[jspm_packages/npm/underscore@1.8.3.js]-%3E[jspm_packages/npm/underscore@1.8.3/underscore.js],[cards/deck.js]-%3E[cards/card.js],[cards/deck.js]-%3E[jspm_packages/npm/underscore@1.8.3.js],[klondike/piles/tableauPile.js]-%3E[jspm_packages/npm/babel-runtime@5.8.25/core-js/object/create.js],[klondike/piles/tableauPile.js]-%3E[klondike/piles/pile.js],[klondike/piles/tableauPile.js]-%3E[jspm_packages/npm/underscore@1.8.3.js],[klondike/piles/remainderPile.js]-%3E[jspm_packages/npm/babel-runtime@5.8.25/core-js/object/create.js],[klondike/piles/remainderPile.js]-%3E[klondike/piles/pile.js],[klondike/piles/foundationPile.js]-%3E[jspm_packages/npm/babel-runtime@5.8.25/core-js/object/create.js],[klondike/piles/foundationPile.js]-%3E[klondike/piles/pile.js],[jspm_packages/github/angular/bower-angular-route@1.4.7.js]-%3E[jspm_packages/github/angular/bower-angular-route@1.4.7/angular-route.js],[jspm_packages/npm/babel-runtime@5.8.25/helpers/create-class.js]-%3E[jspm_packages/npm/babel-runtime@5.8.25/core-js/object/define-property.js],[jspm_packages/npm/babel-runtime@5.8.25/core-js/object/create.js]-%3E[jspm_packages/npm/core-js@1.2.1/library/fn/object/create.js],[jspm_packages/github/angular/bower-angular-route@1.4.7/angular-route.js]-%3E[jspm_packages/github/angular/bower-angular@1.4.7.js],[jspm_packages/npm/babel-runtime@5.8.25/core-js/object/define-property.js]-%3E[jspm_packages/npm/core-js@1.2.1/library/fn/object/define-property.js],[jspm_packages/npm/core-js@1.2.1/library/fn/object/create.js]-%3E[jspm_packages/npm/core-js@1.2.1/library/modules/$.js],[jspm_packages/npm/core-js@1.2.1/library/fn/object/define-property.js]-%3E[jspm_packages/npm/core-js@1.2.1/library/modules/$.js]
) ) This is perfect to evaluate which dependencies SystemJS is seeing / loading... For free, out of the box... 

So, yes, me too I'm a big fan of JSPM and SystemJS....

The code:

System.trace = true;

// Build an array of modules....
window.showModuleRelationships = function () {
    var modules = Object.keys(System.loads).map(function (moduleName) {
        return System.loads[moduleName];
    });

    // This function removes (still hard coded) the beginning of the ES6 Module names
    function displayName(module) {
        return module
            .replace(System.baseURL, ""); // System.baseURL is replacing "http://127.0.0.1:8080/app/"
    }

    // Build a little format so that the yuml site it understands..
    var moduleDefinitions = modules.map(function (module) {
        var name = displayName(module.name);
        return "[" + name + "|" + module.metadata.format + "]";
    });

    var dependencyDefinitions = [];

    modules
        .filter(function (module) {
            return module.deps.length > 0;
        })
        .forEach(function (module) {
            var name = displayName(module.name);

            var dependencies = module.deps
                .map(function (dependency) {
                    return System.normalizeSync(dependency, module.name, module.address)
                })
                .map(displayName)
                .map(function (dependencyName) {
                    return "[" + name + "]->[" + dependencyName + "]"
                });

            dependencyDefinitions = dependencyDefinitions.concat(dependencies);
        });

    var definitions = moduleDefinitions.concat(dependencyDefinitions);

    window.open("http://yuml.me/diagram/plain/class/" + definitions);

};

**Comment by Dutchboy** [comment]
Closing this issue - does it mean you're not considering JSPM?

**Comment by marvinscharle** [comment]
Of course we are considering JSPM - but not for this project at the current state
