### ISSUE TITLE
How to provide two module option like commonjs and system in tsconfig.json?

### ISSUE THREAD

**Issue by thangam105** [conclurer/ionic2-systemjs#25]

**Comment by marvinscharle** [comment]
You can't do this inside one tsconfig. But you can use multiple tsconfig files with modules like `gulp-typescript`.

**Comment by thangam105** [comment]
I have used the commonjs module in tsconfig.json and import the third party component in ionic pages by "typings install file:./customComponent.ts --global --save".I got compile error like module name not found app/pages/page1/home.ts.

How to resolve this?
