### ISSUE TITLE
/build/dependencies.js not there after npm install/ionic serve...

### ISSUE THREAD

**Issue by WilldelaVega777** [conclurer/ionic2-systemjs#33]
can it be caused by this?

Error on fetch for @angular/forms.js at file:///Users/mac/Documents/PROJECTS/LEARNING/Wijmo/ionic2-systemjs/node_modules/@angular/forms.js
        Loading ionic-angular/config/directives.js
        Loading ionic-angular
        Loading app/dist/app.js
        Error: ENOENT: no such file or directory, open '/Users/mac/Documents/PROJECTS/LEARNING/Wijmo/ionic2-systemjs/node_modules/@angular/forms.js'
    at Error (native)

**Comment by WilldelaVega777** [comment]
Seems like there is some compatibility issues between ionic beta 10 and angular forms 0.2.0 (which btw is not included in the package.json depenencies, however when you run npm install it warns the module needs to be installed, if I don't install it then gulp build wouldn't work).  For all what it seems ionic components and config are expecting to find a "forms.js" file under the node_modules/@angular folder, I just replaced (in ionic) occurrences of "@angular/forms" for "@angular/forms/index" in the node_modules/ionic-angular/config and components folder and it seems to be working now.  I am not saying this is the right solution, but instead that there seems to be some version issues.  It would be great to have your opinion on this and if possible to get this fixed the right way in order to be able to proceed coding my project with the assurance that the foundation is right.  I wish I could provide more insight into this, but my experience with the angular 2 dependencies is at this point limited. I guess it is a little bit of a moving target right now.

**Comment by Inoverse** [comment]
Hi,
yes this is right. The template is currently not compatible to the new Angular Forms. We have to upgrade it to Ionic Beta 11. But it takes a while because there are some breaking changes. It is releate to #43 

I let you know, when it's updated.

**Comment by Inoverse** [comment]
Should be fixed now.
